
(()=>{const d=document;const dialog=d.querySelector('[data-menu]');const open=d.querySelector('[data-menu-open]');const close=d.querySelector('[data-menu-close]');if(dialog&&open&&close){const shut=(restore=true)=>{if(dialog.open)dialog.close();open.setAttribute('aria-expanded','false');if(restore)open.focus()};open.addEventListener('click',()=>{dialog.showModal();open.setAttribute('aria-expanded','true');close.focus()});close.addEventListener('click',()=>shut());dialog.addEventListener('cancel',e=>{e.preventDefault();shut()});dialog.addEventListener('click',e=>{if(e.target===dialog)shut()});dialog.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>shut(false)))}const links=[...d.querySelectorAll('[data-preview-index]')];const frames=[...d.querySelectorAll('[data-preview-frame]')];const cap=d.querySelector('[data-preview-caption]');function activate(i){frames.forEach((f,n)=>f.classList.toggle('active',n===i));if(cap&&links[i])cap.textContent=links[i].dataset.caption||''}links.forEach((a,i)=>{a.addEventListener('mouseenter',()=>activate(i));a.addEventListener('focus',()=>activate(i))});})();

(() => {
const d=document, reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches, save=()=>!!(navigator.connection&&navigator.connection.saveData), mobile=()=>matchMedia('(max-width:760px)').matches;
function off(m){if(!m)return;const v=m.querySelector('[data-motion-video]');if(!v)return;v.pause();m.classList.remove('is-playing');v.removeAttribute('src');v.load()}
function on(m){if(!m||reduced()||save())return;const v=m.querySelector('[data-motion-video]');if(!v)return;const src=mobile()?v.dataset.motionMobile:v.dataset.motionDesktop;if(v.getAttribute('src')!==src){v.src=src;v.load()}const p=v.play();if(p&&p.then)p.then(()=>m.classList.add('is-playing')).catch(()=>m.classList.remove('is-playing'))}
const frames=[...d.querySelectorAll('.hero-preview .preview-frame')];function sync(){frames.forEach(f=>f.classList.contains('active')?on(f.querySelector('.motion-media')):off(f.querySelector('.motion-media')))}if(frames.length){const mo=new MutationObserver(sync);frames.forEach(f=>mo.observe(f,{attributes:true,attributeFilter:['class']}));sync()}
d.querySelectorAll('[data-motion-surface="project"]').forEach(m=>{if(!('IntersectionObserver'in window)){on(m);return}new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting?on(m):off(m)),{rootMargin:'120px 0px',threshold:.05}).observe(m)});
})();
